name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    tags:        
      - v*.*.*           # Push events to v1.0.0, v1.1.1, v2.0.1, etc

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Check cache
      id: verify-cache
      run: |
        echo "::set-output name=heads::`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/xybp888/iOS-SDKs | head -n 1 | cut -f 1`"

    - name: Use cache
      id: cache
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/theos
        key: ${{ runner.os }}-v2-${{ steps.verify-cache.outputs.heads }}

    - name: Prepare Theos
      uses: NyaMisty/theos-action@master
      with:
        theos-sdks: 'https://github.com/xybp888/iOS-SDKs'

    - name: Build package
      run: |
        rm -f packages/*
        make package FINALPACKAGE=1

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ github.workspace }}/packages/*.deb

    #- name: Setup tmate session
    #  if: ${{ failure() }}
    #  uses: mxschmitt/action-tmate@v3
